//
//  ADIFParser.swift
//  ADIF to Excel
//
//  Created by factoreal on 7/30/26.
//

import Foundation

// MARK: - ADIF Parsing & Processing Logic

func parseADIF(content: String) -> (headers: [String], records: [[String: String]]) {
    var records: [[String: String]] = []
    var allKeys = Set<String>()
    
    var body = content
    if let eohRange = content.range(of: "<EOH>", options: .caseInsensitive) {
        body = String(content[eohRange.upperBound...])
    }
    
    var index = body.startIndex
    var currentRecord = [String: String]()
    
    while index < body.endIndex {
        if body[index] == "<" {
            guard let closeBracket = body[index...].firstIndex(of: ">") else { break }
            let tagContent = String(body[body.index(after: index)..<closeBracket])
            let tagUpper = tagContent.uppercased()
            
            if tagUpper == "EOR" {
                if !currentRecord.isEmpty {
                    records.append(currentRecord)
                    currentRecord = [:]
                }
                index = body.index(after: closeBracket)
                continue
            }
            
            let parts = tagContent.split(separator: ":")
            if parts.count >= 2, let len = Int(parts[1]) {
                let fieldName = String(parts[0]).uppercased()
                let valueStart = body.index(after: closeBracket)
                
                var valueEnd = valueStart
                var charsCount = 0
                while valueEnd < body.endIndex && charsCount < len {
                    valueEnd = body.index(after: valueEnd)
                    charsCount += 1
                }
                
                let value = String(body[valueStart..<valueEnd]).trimmingCharacters(in: .whitespacesAndNewlines)
                currentRecord[fieldName] = value
                allKeys.insert(fieldName)
                
                index = valueEnd
                continue
            } else {
                index = body.index(after: closeBracket)
                continue
            }
        } else {
            index = body.index(after: index)
        }
    }
    
    if !currentRecord.isEmpty {
        records.append(currentRecord)
    }
    
    let priorityHeaders = ["QSO_DATE", "TIME_ON", "CALL", "FREQ", "BAND", "MODE", "RST_SENT", "RST_RCVD", "NAME", "QTH", "COMMENT"]
    var headers: [String] = []
    
    for item in priorityHeaders {
        if allKeys.contains(item) {
            headers.append(item)
            allKeys.remove(item)
        }
    }
    headers.append(contentsOf: Array(allKeys).sorted())
    
    return (headers, records)
}

func generateADIF(originalContent: String, records: [[String: String]]) -> String {
    var header = "Generated by ADIF Processor (Developed by EP2AES)\r\n<EOH>\r\n"
    if let eohRange = originalContent.range(of: "<EOH>", options: .caseInsensitive) {
        header = String(originalContent[..<eohRange.upperBound]) + "\r\n"
    }
    
    var body = ""
    let priorityKeys = ["QSO_DATE", "TIME_ON", "CALL", "FREQ", "BAND", "MODE", "RST_SENT", "RST_RCVD", "NAME", "QTH", "COMMENT"]
    
    for record in records {
        var recordStr = ""
        var remainingKeys = Set(record.keys)
        
        for key in priorityKeys {
            if let val = record[key], !val.isEmpty {
                recordStr += "<\(key):\(val.count)>\(val)"
                remainingKeys.remove(key)
            }
        }
        
        for key in remainingKeys.sorted() {
            if let val = record[key], !val.isEmpty {
                recordStr += "<\(key):\(val.count)>\(val)"
            }
        }
        
        recordStr += "<EOR>\r\n"
        body += recordStr
    }
    
    return header + body
}

func generateCSV(headers: [String], records: [[String: String]]) -> String {
    var lines: [String] = []
    
    let headerRow = headers.map { escapeCSV($0) }.joined(separator: ",")
    lines.append(headerRow)
    
    for record in records {
        let row = headers.map { header in
            let val = record[header] ?? ""
            return escapeCSV(val)
        }.joined(separator: ",")
        lines.append(row)
    }
    
    return lines.joined(separator: "\r\n")
}

func normalizeTime(_ timeStr: String) -> String {
    let digits = timeStr.filter { $0.isNumber }
    if digits.count == 4 {
        return digits + "00"
    } else if digits.count < 6 {
        return digits.padding(toLength: 6, withPad: "0", startingAt: 0)
    }
    return String(digits.prefix(6))
}

func escapeCSV(_ field: String) -> String {
    if field.contains(",") || field.contains("\"") || field.contains("\n") || field.contains("\r") {
        let escaped = field.replacingOccurrences(of: "\"", with: "\"\"")
        return "\"\(escaped)\""
    }
    return field
}
