import Foundation
#if STANDALONE_ADIF
// Run alone:  swiftc -D STANDALONE_ADIF -parse-as-library Tests/ADIFLengthRegression.swift YAAM/ADIFParser.swift -o /tmp/adif && /tmp/adif
// These two stand-ins are the only outside symbols generateADIF touches.
enum QSOMetadataFormatter { static func cleanComment(_ s: String) -> String { s.trimmingCharacters(in: .whitespacesAndNewlines) } }
enum AmateurBandPlan { static func effectiveADIFMode(mode: String, submode: String, frequencyMHz: Double?) -> String { mode } }
#else
@testable import YAAM
#endif

@main
struct ADIFLengthRegression {
    static func main() {
        testWriterCountsUnicodeCharacters()
        testRoundTripNonASCII()
        testLegacyCharacterCountedFileStillLoads()
        testByteCountedFiles()
        testUTF16AndUnicodeCountedFiles()
        testSpecCRLFMultiline()
        testLastFieldDoesNotMergeRecords()
        testLatin1DecodedFile()
        testHeaderlessLowercaseAndEdgeValues()
        print("ADIF length regression tests passed.")
    }

    private static func records(_ text: String) -> [[String: String]] { parseADIF(content: text).records }

    private static func testWriterCountsUnicodeCharacters() {
        let out = generateADIF(originalContent: "", records: [["CALL": "W1AW", "MODE": "CW", "NAME": "José", "NOTES": "a\r\nb"]])
        precondition(out.contains("<NAME:4>José"), "LENGTH counts Unicode characters, like Wavelog")
        precondition(out.contains("<NOTES:4>a\r\nb"), "CR LF counts as two, as in the spec's MultilineString")
        precondition(generateADIF(originalContent: "", records: [["CALL": "W1AW", "MODE": "CW", "COMMENT": "73 José"]]).contains("<COMMENT:7>73 José"))
    }

    private static func testRoundTripNonASCII() {
        let source: [[String: String]] = [
            ["CALL": "W1AW", "MODE": "CW", "NAME": "Josep Mª Solé", "QTH": "Sant Cugat del Vallès",
             "COMMENT": "73 José 👍🏽", "ADDRESS": "Carrer d'Ausiàs March, 12", "NOTES": "line one\r\nline two\r\nline three"],
            ["CALL": "K1AB", "MODE": "SSB", "QTH": "東京"]
        ]
        precondition(records(generateADIF(originalContent: "", records: source)) == source, "YAAM must read back what it writes")
    }

    private static func testLegacyCharacterCountedFileStillLoads() {
        // What generateADIF wrote before this change: Characters (CR LF = 1), except COMMENT (bytes).
        let legacy = "Generated by ADIF Processor (Developed by EP2AES)\r\n<EOH>\r\n"
            + "<CALL:4>W1AW<MODE:2>CW<NAME:13>Josep Mª Solé<QTH:21>Sant Cugat del Vallès<COMMENT:8>73 José<GRIDSQUARE:4>FN31<EOR>\r\n"
            + "<CALL:4>K1AB<MODE:3>SSB<EOR>\r\n"
        let r = records(legacy)
        precondition(r.count == 2)
        precondition(r[0]["NAME"] == "Josep Mª Solé" && r[0]["QTH"] == "Sant Cugat del Vallès")
        precondition(r[0]["COMMENT"] == "73 José" && r[0]["GRIDSQUARE"] == "FN31")
        let notes = "<EOH><CALL:4>W1AW<NOTES:17>line one\r\nline two<GRIDSQUARE:4>FN31<EOR>"
        precondition(records(notes)[0]["NOTES"] == "line one\r\nline two" && records(notes)[0]["GRIDSQUARE"] == "FN31")
    }

    private static func testByteCountedFiles() {
        // FieldLogExporter / Wavelog / zero-click upload shape: bytes plus a trailing space, 2+ non-ASCII in a field.
        let text = "<ADIF_VER:5>3.1.4 <EOH>\n<CALL:4>W1AW <NAME:15>Josep Mª Solé <QTH:22>Sant Cugat del Vallès <EOR>\n<CALL:4>K1AB <EOR>\n"
        let r = records(text)
        precondition(r.count == 2 && r[0]["NAME"] == "Josep Mª Solé" && r[0]["QTH"] == "Sant Cugat del Vallès")
        let bare = "<EOH><NAME:5>José<QTH:6>Girona<COMMENT:11>73 👍🏽<EOR>"
        precondition(records(bare) == [["NAME": "José", "QTH": "Girona", "COMMENT": "73 👍🏽"]])
    }

    private static func testUTF16AndUnicodeCountedFiles() {
        // WSJT-X counts UTF-16 units (QString::length): 👍 is 2.
        precondition(records("<EOH><CALL:4>W1AW<COMMENT:5>73 👍<QTH:6>Girona<EOR>") == [["CALL": "W1AW", "COMMENT": "73 👍", "QTH": "Girona"]])
        // Wavelog counts Unicode characters (mb_strlen): a multi-line NOTES with an accent.
        precondition(records("<EOH><CALL:4>W1AW<NOTES:7>José\r\nx<QTH:6>Girona<EOR>") == [["CALL": "W1AW", "NOTES": "José\r\nx", "QTH": "Girona"]])
    }

    private static func testSpecCRLFMultiline() {
        let address = "Name\r\n1 Main St\r\nSpringfield"
        let text = "<ADIF_VER:5>3.1.6\r\n<EOH>\r\n<CALL:4>W1AW <ADDRESS:\(address.utf8.count)>\(address) <GRIDSQUARE:4>FN31 <EOR>\r\n"
        precondition(records(text) == [["CALL": "W1AW", "ADDRESS": address, "GRIDSQUARE": "FN31"]])
        precondition(records("<CALL:4>W1AW<ADDRESS:22>1 Main St\r\nSpringfield<GRIDSQUARE:4>FN31<EOR>")[0]["GRIDSQUARE"] == "FN31")
    }

    private static func testLastFieldDoesNotMergeRecords() {
        for text in [
            "<EOH><CALL:4>W1AW<NAME:15>Muñoz Sánchez<EOR><CALL:4>K1AB<EOR><CALL:4>N1CC<EOR>",   // bytes
            "<EOH><CALL:4>W1AW<NAME:13>Muñoz Sánchez<EOR><CALL:4>K1AB<EOR><CALL:4>N1CC<EOR>",   // characters
            "<EOH><CALL:4>W1AW<NOTES:7>a\r\nb\r\nc<EOR><CALL:4>K1AB<EOR><CALL:4>N1CC<EOR>"        // spec CR LF
        ] {
            let r = records(text)
            precondition(r.count == 3 && r[0]["CALL"] == "W1AW" && r[1]["CALL"] == "K1AB" && r[2]["CALL"] == "N1CC")
        }
    }

    private static func testLatin1DecodedFile() {
        // Files are decoded as UTF-8 first and ISO Latin-1 second; LENGTH there is one byte per character.
        var data = Data("<EOH><NAME:4>Jos".utf8)
        data.append(0xE9)
        data.append(Data("<QTH:6>Girona<EOR>".utf8))
        precondition(String(data: data, encoding: .utf8) == nil)
        let text = String(data: data, encoding: .utf8) ?? String(data: data, encoding: .isoLatin1) ?? ""
        precondition(records(text) == [["NAME": "José", "QTH": "Girona"]])
    }

    private static func testHeaderlessLowercaseAndEdgeValues() {
        precondition(records("<CALL:4>W1AW<BAND:3>20M<EOR><CALL:4>K1AB<EOR>").count == 2, "headerless")
        precondition(records("x\n<eoh>\n<call:4>W1AW<eor><call:4>K1AB<eor>").map { $0["CALL"] } == ["W1AW", "K1AB"], "lowercase tags")
        precondition(records("<EOH><COMMENT:7>a<b>c<d<QTH:6>Girona<EOR>") == [["COMMENT": "a<b>c<d", "QTH": "Girona"]], "'<' inside a value")
        precondition(records("<EOH><CALL:4>W1AW<NAME:0><QTH:6>Girona<EOR>") == [["CALL": "W1AW", "NAME": "", "QTH": "Girona"]], "<NAME:0>")
    }
}
